### PR TITLE
#51 change table format

### PR DESCRIPTION
**Pull request by krzysiekwie**
fixes https://github.com/canonical/open-documentation-academy/issues/51

### CODE REVIEW

**Comment by k-dimple** [comment]
Hi @krzysiekwie, thanks for this! It looks good. Could you make one small change though - let's not make any of the content within the tables bold. The headers are bold and I think that should be good enough.

**Comment by k-dimple** [comment]
Also, once you are done with the changes, could you try to squash your commits into one so that we can keep a clean commit history. Thanks! :)

**Comment by krzysiekwie** [comment]
@k-dimple : removed bold below the headers and squashed

**Comment by k-dimple** [comment]
oops it looks like you have included earlier commits from other contributors and there are now 9 commits in total. I just wanted you to squash your 3 or 4 commits into a single commit. Unfortunately I won't be able to merge this as this.

If you don't mind, could you create a new PR with just your changes to the single file (as a single commit)? If not, I'll include those changes and close the issue as done in the open docs academy repo.

**Comment by krzysiekwie** [comment]
closing this one, added https://github.com/canonical/ubuntu-cloud-docs/pull/208

**Pull request closed without merging**
