### PR TITLE
[AWS] Update instructions for enabling GPUs on EKS. 

### PR DESCRIPTION
**Pull request by k-dimple**
Addresses issues [#281](https://github.com/canonical/ubuntu-cloud-docs/issues/281) and [#282](https://github.com/canonical/ubuntu-cloud-docs/issues/282).

### CODE REVIEW

**Comment by k-dimple** [comment]
@carlosbravoa could you give these [updated instructions](https://canonical-ubuntu-documentation-library--284.com.readthedocs.build/aws/en/284/aws-how-to/kubernetes/enable-gpus-on-eks/) a try whenever you get the chance? Thanks!

**Review by rpocase — APPROVED** [review]
thanks for taking care of this! one less thing for us to do next pulse :)

**Comment by carlosbravoa** [comment]
@k-dimple @rpocase I didn't write this one, so I would have to do some research first (it doesn't look tough, but I cannot commit without assessing it first. Thanks). But yeah, if the team is too tight, I can take it.

**Comment by k-dimple** [comment]
Sorry @carlosbravoa, I was a little confused about who had written it. Thanks for offering to take it up! Maybe you could try a quick assessment and let us know in case it is problematic, and Jess or someone else from the team can then give it a shot.

**Pull request merged**
