### PR TITLE
feat: add glossary like list of abbreviations

### PR DESCRIPTION
**Pull request by toabctl**
Following the mkdocs documentation[0] to add tooltips for
abbreviations so it's easier to understand what the different
abbreviations mean.

Refs:
- [0] https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-a-glossary

### CODE REVIEW

**Comment by j5awry** [comment]
Hm...i'm not sure i like it either. 

- no public glossary, just tooltips
- it gets _really_ messy looking. on the front page, even with only 4 items, there are 9 underlines with tooltips.
- more messy : because we use some of the abbreviations in there in paths, you'll see a path with a tooltip. 

but maybe that's not such a terrible thing? I dunno, i'm not a documentation expert, just feels messy visually to me...

as to the public...i have a possibly bad idea. add a script that during the build that:

* copies `includes/abbreviations.md` to `docs/reference/abbreviations.md`
* adds a space after the `*`, thus making it a bulleted list

Magic abbreviations page.

we could do the same with other terms by making `includes/glossary.md`.

**Comment by toabctl** [comment]
> we could do the same with other terms by making `includes/glossary.md`.

or use a tool that is good for writing documentation like Sphinx 😄 But then having different formats for internal and external doc is also not nice...

**Comment by toabctl** [comment]
> Hm...i'm not sure i like it either.
> 
> * no public glossary, just tooltips
> * it gets _really_ messy looking. on the front page, even with only 4 items, there are 9 underlines with tooltips.
> * more messy : because we use some of the abbreviations in there in paths, you'll see a path with a tooltip.
> 
> but maybe that's not such a terrible thing? I dunno, i'm not a documentation expert, just feels messy visually to me...

same here.

> as to the public...i have a possibly bad idea. add a script that during the build that:
> 
> * copies `includes/abbreviations.md` to `docs/reference/abbreviations.md`
> * adds a space after the `*`, thus making it a bulleted list
> 
> Magic abbreviations page.

yeah. but it would still doesn't look nice.

> we could do the same with other terms by making `includes/glossary.md`.

or use a tool that is good for writing documentation like Sphinx 😄 But then having different formats for internal and external doc is also not nice...

**Comment by j5awry** [comment]
We can close this PR without merging. We can ask @k-dimple about a glossary

**Pull request closed without merging**
